title: Lee Se Geon
logo: null
author: themefisher
description: this is meta description
email: dltprjs1@naver.com
phone: 010 - 7724 - 7848
address: 서울특별시 금천구 벚꽃로 14길 5
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)
menu:
- name: About
  link: /about
- name: skills
  link: /blog
- name: Portfolio
  link: /portfolio
- name: Contact
  link: /contact
google-analytics: null
hero:
  hero-title: 책임감을 가지고<br> 충실히 임하는 <br> 개발자 이세건입니다.
social:
- icon: ti-facebook
  link: '#'
- icon: ti-instagram
  link: https://www.instagram.com/?next=%2F
- icon: ti-github
  link: https://github.com/dltprjs1
blurb: 어려운 난관에 맞닥뜨려도 해결할 때까지 놓지 않는 개발자 이세건입니다. <br> 끊임없이 노력하는 개발자가 되겠습니다.<br> 어느 곳에 가더라도 함께하는 개발자가 되겠습니다.
blurb-btn-link: /about
blurb-btn-name: know more
work-process:
- title: (주)넷틴스
  icon: assets/images/experience/icon-2.png
  content: 소프트웨어 유지보수 및 개발, 웹 개발 및 유지보수 <br> 2023.03 - 2024.03
- title: (주)경남지오영
  icon: assets/images/experience/icon-1.png
  content: 자재관리 <br> 2021.05 - 2022.06
- title: (주)NEK
  icon: assets/images/experience/icon-3.png
  content: 생산 기계 설비 수리 금형 교환 <br> 2017.12 - 2019.12
Language-process:
- title: Java
  icon: assets/images/skills/java.png
- title: Python
  icon: assets/images/skills/python.png
- title: delphi
  icon: assets/images/skills/delphi.png
FrontEnd-process:
- title: HTML5
  icon: assets/images/skills/html5.png
- title: CSS
  icon: assets/images/skills/css.png
- title: JavaScript(Jquery)
  icon: assets/images/skills/js.png
- title: BootStrap
  icon: assets/images/skills/bootstrap.png
BackEnd-process:
- title: Spring
  icon: assets/images/skills/Spring.png
- title: Spring FrameWork
  icon: assets/images/skills/Spring.png
- title: MyBatis
  icon: assets/images/skills/mybatis.png
- title: SQL/PL
  icon: assets/images/skills/sql.png
DataBase-process:
- title: Oracle
  icon: assets/images/skills/oracle.png
- title: MSSQL
  icon: assets/images/skills/mssql.png
- title: MYSQL
  icon: assets/images/skills/mysql.png
Tool-process:
- title: Eclipse
  icon: assets/images/skills/eclipse.png
- title: STS(Spring-Tool-Suite)
  icon: assets/images/skills/spring.png
- title: Visual Studio Code
  icon: assets/images/skills/vscode.png
- title: IntelliJ
  icon: assets/images/skills/intellij.png
- title: GitHub
  icon: assets/images/skills/github.png
blog-btn-link: /blog
skills-title: Skills
skills:
- name: FrontEnd
  color: '#9473e6'
  value: 50%
- name: BackEnd
  color: '#bdecf6'
  value: 80%
- name: DataBase(DB)
  color: '#ffffa6'
  value: 60%
experience-title: Experience
experience:
- name: Junior UX Designer
  icon: icon-1.png
  date: Jan 2007 - Feb 2009
  organization: WEBEX
- name: UX & UI Designer
  icon: icon-2.png
  date: Mar 2009 - Aug 2014
  organization: AUGMEDIX
- name: Senior UI Designer
  icon: icon-3.png
  date: Sep 2014 - Present
  organization: THEMEFISHER
education-title: Education
education:
- name: KH정보교육원
  date: 2021.7 - 2022.12
  organization: (스마트웹&콘텐츠개발)스마트웹&콘텐츠 웹애플리케이션 개발자 양성과정
- name: 경남도립 남해대학교
  date: 2012.3 - 2014.6
  organization: 메카트로닉스과
- name: 칠원고등학교
  date: 2009.3 - 2012.2
  organization: 이과계열

portfolio-home-items:
- image: assets/images/portfolio/코인로고.png
  url: '/autotrading'
- image: assets/images/portfolio/sang_logo.png
  url: '/SangGym'
- image: assets/images/portfolio/cowork.png
  url: '/cowork'
- image: assets/images/portfolio/challengers.png
  url: 'challengers'

portfolio-label:
- title: JAVA
  type: JAVA
- title: PYTHON
  type: PYTHON

portfolio-items:
- image: assets/images/portfolio/코인로고.png
  url: '/autotrading'
  portfolio-type:
  - type:
    
- image: assets/images/portfolio/sang_logo.png
  url: '/SangGym'
  portfolio-type:
  - type: JAVA
  
- image: assets/images/portfolio/cowork.png
  url: '/cowork'
  portfolio-type:
  - type: JAVA
  
- image: assets/images/portfolio/challengers.png
  url: '/challengers'
  portfolio-type:
  - type: JAVA

testimonial-items:
- image: assets/images/portfolio/challengers/관리자메인.png
  content: <h4>5인 팀 프로젝트</h4><br> 제가 맡은 기능은 관리자 페이지입니다. <br> 관리자 메인페이지에는 총 6개의 카테고리로 나뉘어져 있습니다. 상단에는 include를 통해 관리자 모든 페이지에 위와 같이 로고 , 관리자 홈 , 회원 신고 관리 , 카테고리 관리 , 자주하는 질문 관리 , 1:1문의 관리로 이동이 가능하고 메인에는 총 6개로 상단의 페이지를 포함하여 챌린지 관리 , 관리자 권한 챌린지 만들기 페이지로 나뉩니다.
  
- image: assets/images/portfolio/challengers/회원신고관리.png
  content: 회원 신고 관리 페이지 입니다. <br> 메인에는 테이블 형식으로 회원 신고 목록을 볼 수 있으며 상단에는 검색 하단에는 페이징 처리가 되어있습니다. ajax를 활용하여 피신고자 , 신고자 , 제목을 통해 검색 할 수 있으며 페이징 처리 또한 ajax를 활용하였습니다. 목록을 클릭하여 회원을 삭제 또는 회원 정지 기능이 있습니다.  

- image: assets/images/portfolio/challengers/카테고리관리.png
  content: 카테고리 관리 페이지 입니다. <br> 메인 카테고리 총 9개로 이루어져 있고, 클릭하여 상세 페이지로 이동하면 카테고리 수정 , 삭제 기능이 있고 서브 카테고리 추가 , 수정 , 삭제 기능이 있습니다.

- image: assets/images/portfolio/challengers/자주하는질문관리.png
  content: 해당 페이지는 자주하는 질문 관리 페이지입니다. <br> 회원 신고 관리 페이지와 마찬가지로 상단에는 검색과 네 개의 카테고리가 있고 하단에는 페이징 처리가 되어있으며 중단에는 자주하는 질문 목록들이 나열되어있습니다. 검색과 페이징은 ajax를 통해 기능하며 목록을 클릭하여 상세보기 페이지로 이동하게 되면 추가 , 수정 , 삭제 기능이 있습니다.

- image: assets/images/portfolio/challengers/일대일문의관리.png
  content: 1:1문의 관리 페이지입니다. <br> 프로젝트 당시 관리자 페이지는 디자인 보다는 UI/UX의 편리성과 친절성이 중요하다고 생각하여 전체적으로 일관성이 있게 디자인 하였습니다. 질문 목록을 클릭하여 상세보기 페이지로 이동하게 되면 회원에게 답변을 하고 회원은 메인 include에 메일 이모티콘과 답변의 갯수가 생성됩니다.   

- image: assets/images/portfolio/challengers/챌린지관리.png
  content: 챌린지 관리 페이지입니다. <br> 회원 페이지에서 챌린지를 생성하거나 관리자 권한으로 챌린지를 생성한 모든 챌린지를 9개의 카테고리로 나타냅니다. 다른 기능들과 마찬가지로 상단에는 검색과 카테고리 목록 하단에는 페이징 처리가 되어있으며 한 페이지에 12개의 챌린지로 나뉘어 있습니다. 해당 챌린지를 클릭하여 상세보기 페이지로 이동하게 되면, 챌린지의 모든 설정들을 변경할 수 있습니다.
  
- image: assets/images/portfolio/challengers/챌린지개설.png
  content: 관리자 챌린지 개설 페이지입니다. <br> 챌린지 개설은 총 5단계로 이루어져 있습니다. <br> 1.세 개의 채크박스를 클릭하여 다음 단계로 넘어 갈 수 있습니다. <br> 2.다른 회원들에게 챌린지의 공개 유무를 결정합니다. <br> 3.챌린지의 제목 , 인증 방법 , 인증 빈도 , 기간을 정하고 예시 사진을 확인 후 다음 페이지로 넘어 갈 수 있습니다. <br> 4.인증가능 시간과 챌린지 소개 , 소개 사진을 작성 후 마지막 단계로 이동합니다. <br>5.예치금과 비공개 참여 코드 , 최대인원 설정후 챌린지를 개설할 수 있습니다.  
 
challnegers-process:
- icon: assets/images/skills/java.png
- icon: assets/images/skills/html5.png
- icon: assets/images/skills/css.png
- icon: assets/images/skills/js.png
- icon: assets/images/skills/bootstrap.png
- icon: assets/images/skills/jsp.png
- icon: assets/images/skills/oracle.png
- icon: assets/images/skills/eclipse.png
- icon: assets/images/skills/github.png 



testimonial2-items:
- image: assets/images/portfolio/cowork/프로젝트관리.png
  content: <h4>5인 팀 프로젝트</h4><br> 제가 맡은 기능은 프로젝트 페이지 입니다. <br> 프로젝트 메인 페이지는 상단에 include를 이용하여 캘린더 , 프로젝트 , 메모 , 주소록 , 메일 , 채팅창으로 이동이 가능하고 좌측에는 table형식 보기 버튼과 Status와 Member 필터링 기능이 있습니다.
  
- image: assets/images/portfolio/cowork/프로젝트Drag.png
  content: 프로젝트 페이지 기능 입니다. <br> Jquery에서 제공하는 sortable 함수와 option으로는 handle , connectwith , start , update , receive를 이용하여 하나의 프로젝트를 이동할 경우 ajax를 이용하여 status의 프로젝트가 업데이트 되도록 하였습니다. 가장 우측으로는 status 추가 기능이 있고 , status 아래 부분에는 프로젝트 추가기능이 있습니다.   

- image: assets/images/portfolio/cowork/프로젝트Modal.png
  content: 프로젝트를 클릭하였을때 생성되는 상세보기 모달 페이지입니다. <br> 모든 기능은 ajax를 활용하였고 최상단에 프로젝트 , 상단에 Member 구성이 있습니다 member는 popover를 이용하여 해당 멤버의 정보를 보거나 프로젝트로부터 제외시킬 수 있고 '+'버튼을 클릭하여 멤버를 추가할 수 있습니다. member구성 아래에 프로젝트의 상세내용을 추가 하거나 수정할 수 있고 댓글을 달거나 수정 삭제할 수 있습니다. 우측에는 프로젝트 시작일과 마감일을 date picker API를 활용하여 추가 수정이 가능하고 모달창에서 Status 변경이 가능합니다.

- image: assets/images/portfolio/cowork/프로젝트테이블.png
  content: 프로젝트를 Table 형식으로 나타내는 페이지입니다. 상단에는 프로젝트와 멤버를 검색할 수 있고 좌측에는 Status별로 프로젝트 목록을 확인 할 수 있습니다. 하단에는 페이징과 프로젝트 추가하기 기능이있습니다. 해당 프로젝트를 클릭할 경우 Modal창을 띄울 수 있습니다.  
 
cowork-process:
- icon: assets/images/skills/java.png
- icon: assets/images/skills/html5.png
- icon: assets/images/skills/css.png
- icon: assets/images/skills/js.png
- icon: assets/images/skills/bootstrap.png
- icon: assets/images/skills/spring.png
- icon: assets/images/skills/oracle.png
- icon: assets/images/skills/mybatis.png
- icon: assets/images/skills/spring.png
- icon: assets/images/skills/github.png 


testimonial3-items:
- image: 
  content: <h4>개별 프로젝트</h4><br> 총 세 개의 구성으로 이루어진 프로젝트 입니다. <br>1. 자동 선물 프로그램 <br>2. 데이터 처리 서버 <br> 3. 프로그램 설정 및 데이터 집계 페이지 <br> 프로그램에서 주문 조건을 찾아 주문 하는 형식의 프로그램입니다. <br> 주문 조건과 계좌 데이터 주문 처리에 대한 데이터를 서버로 전송하도록 개발하였습니다.<br> 서버에서는 받은 데이터를 웹페이지 프로젝트로 송신 및 데이터베이스 저장 <br> 웹페이지에서는 서버에서 받은 데이터 수신 및 노출과 프로그램 설정 기능을 구현하였습니다.  
  
- image: assets/images/portfolio/AutoTrading/Server.png
  content: 프로그램에서 넘어온 데이터를 mybatis로 데이터베이스에 CRUD 및 웹페이지로 데이터 전송 하고 있습니다. 현재는 Windows OS에서 Demon으로 작동하고 있으며 추후 리눅스에서 구현할 계획입니다.
  
- image: assets/images/portfolio/AutoTrading/Web1.png
  content: Socket Client로 Server에서 수신받은 데이터를 활용하여 웹페이지에 실시간으로 데이터 노출 하도록 개발하였습니다.  

autotrading-process:
- icon: assets/images/skills/python.png
- icon: assets/images/skills/vscode.png
- icon: assets/images/skills/java.png
- icon: assets/images/skills/mssql.png
- icon: assets/images/skills/spring.png
- icon: assets/images/skills/mybatis.png
- icon: assets/images/skills/html5.png
- icon: assets/images/skills/css.png
- icon: assets/images/skills/js.png
- icon: assets/images/skills/github.png


testimonial4-items:
- image: assets/video/sanggym.mp4
  content: <h4>개별 프로젝트</h4><br> 취미로 웨이트트레이닝을 하고 있습니다. 제가 다니는 헬스장의 홈페이지가 궁금해서 찾아보았는데 <br> 홈페이지가 존재하지 않다는 것에 아이디어를 얻어 홈페이지를 제작해 보았습니다. home, 센터소개, 프로그램 페이지로 크게 이루어져있고 navermap API와 카카오톡 채널을 개설하여 kakakoAPI를 통해 문의를 하도록 개발 하였습니다. 프로그램 페이지는 PT, 헬스, GX 페이지로 ajax를 통해 실현하였습니다.  
  
- image: assets/video/sang_kakao.mp4
  content: 컴퓨터로 녹화할 경우 전화통화 및 카카오톡 페이지가 송출 되지 않아 휴대폰으로 촬영한 점 양해 부탑드립니다. 우선 contact를 클릭하거나 터치 할 경우 전화연결이 되고 카테고리 창에서 톡상담을 클릭할 경우 SangGYM 채널을 통해 개별적으로 사용자와의 소통이 가능하도록 하였습니다. MVC패턴을 사용하여 헬스장 관리자 페이지를 기획중에 있습니다. 시청해 주셔서 감사합니다!!!



sanggym-process:
- icon: assets/images/skills/java.png
- icon: assets/images/skills/html5.png
- icon: assets/images/skills/css.png
- icon: assets/images/skills/js.png
- icon: assets/images/skills/bootstrap.png
- icon: assets/images/skills/spring.png
- icon: assets/images/skills/intellij.png
- icon: assets/images/skills/github.png

contact-title: Contact Info
contact-email: dltprjs1@naver.com
