title: Lee Se Geon
logo: null
author: themefisher
description: this is meta description
email: dltprjs1@naver.com
phone: 010 - 7724 - 7848
address: 서울특별시 동대문구 휘경동
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)
menu:
- name: About
  link: /about
- name: skills
  link: /blog
- name: Portfolio
  link: /portfolio
- name: Contact
  link: /contact
google-analytics: null
hero:
  hero-title: 책임감을 가지고<br> 충실히 임하는 <br> 개발자 이세건입니다.
social:
- icon: ti-facebook
  link: '#'
- icon: ti-instagram
  link: https://www.instagram.com/?next=%2F
- icon: ti-github
  link: https://github.com/dltprjs1
blurb: 어려운 난관에 맞닥뜨려도 해결할 때까지 놓지 않는 신입 개발자 이세건입니다. <br> 끊임없이 노력하는 개발자가 되겠습니다.<br> 어느 곳에 가더라도 함께하는 개발자가 되겠습니다.
blurb-btn-link: /about
blurb-btn-name: know more
work-process:
- title: (주)경남지오영
  icon: assets/images/experience/icon-1.png
  content: 자재관리 <br> 2021.05 - 2022.06
- title: (주)DY C&F
  icon: assets/images/experience/icon-2.png
  content: 생산관리 <br> 2020.04 - 2021.04
- title: (주)NEK
  icon: assets/images/experience/icon-3.png
  content: 생산 기계 설비 수리 금형 교환 <br> 2017.12 - 2019.12
Language-process:
- title: Java
  icon: assets/images/skills/java.png
- title: Python
  icon: assets/images/skills/python.png
- title: SQL
  icon: assets/images/skills/sql.png
FrontEnd-process:
- title: HTML5
  icon: assets/images/skills/html5.png
- title: CSS
  icon: assets/images/skills/css.png
- title: JavaScript(Jquery)
  icon: assets/images/skills/js.png
- title: BootStrap
  icon: assets/images/skills/bootstrap.png
BackEnd-process:
- title: Spring
  icon: assets/images/skills/spring.png
- title: JSP/JSTL
  icon: assets/images/skills/jsp.png
DataBase-process:
- title: Oracle
  icon: assets/images/skills/oracle.png
- title: MyBatis
  icon: assets/images/skills/mybatis.png
Tool-process:
- title: Eclipse
  icon: assets/images/skills/eclipse.png
- title: STS(Spring-Tool-Suite)
  icon: assets/images/skills/spring.png
- title: Visual Studio Code
  icon: assets/images/skills/vscode.png
- title: GitHub
  icon: assets/images/skills/github.png
blog-btn-link: /blog
skills-title: Skills
skills:
- name: Language
  color: '#fdb157'
  value: 80%
- name: FrontEnd
  color: '#9473e6'
  value: 70%
- name: BackEnd
  color: '#bdecf6'
  value: 80%
- name: DataBase(DB)
  color: '#ffffa6'
  value: 60%
experience-title: Experience
experience:
- name: Junior UX Designer
  icon: icon-1.png
  date: Jan 2007 - Feb 2009
  organization: WEBEX
- name: UX & UI Designer
  icon: icon-2.png
  date: Mar 2009 - Aug 2014
  organization: AUGMEDIX
- name: Senior UI Designer
  icon: icon-3.png
  date: Sep 2014 - Present
  organization: THEMEFISHER
education-title: Education
education:
- name: KH정보교육원
  date: 2021.7 - 2022.12
  organization: (스마트웹&콘텐츠개발)스마트웹&콘텐츠 웹애플리케이션 개발자 양성과정
- name: 경남도립 남해대학교
  date: 2012.3 - 2014.6
  organization: 메카트로닉스과
- name: 칠원고등학교
  date: 2009.3 - 2012.2
  organization: 이과계열
services-title: Services
services:
- name: UI Design
  icon: ti-palette
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  active: null
- name: UX Design
  icon: ti-vector
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  active: true
- name: Interaction Design
  icon: ti-panel
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  active: null
portfolio-home-items:
- image: assets/images/portfolio/challengers.png
  url: '/portfolio_detail'
- image: assets/images/portfolio/cowork.png
  url: '/portfolio_detail'
- image: assets/images/portfolio/item-3.png
  url: '/portfolio_detail'
- image: assets/images/portfolio/item-4.png
  url: '/portfolio_detail'
- image: assets/images/portfolio/item-5.png
  url: '/portfolio_detail'

portfolio-label:
- title: JSP
  type: design
- title: SPRING
  type: branding
- title: PYTHON
  type: illustration
portfolio-items:
- image: assets/images/portfolio/challengers.png
  url: '/portfolio_detail'
  portfolio-type:
  - type: 관리자 페이지 전체 담당
  - type: JSP , HTML5 , CSS , OracleDB , BootStrap , JavaScript(Jquery) , github , notion , Discord
- image: assets/images/portfolio/cowork.png
  url: '/portfolio_detail'
  portfolio-type:
  - type: 프로젝트 관리 페이지 담당
- image: assets/images/portfolio/item-3.png
  url: '/portfolio_detail'
  portfolio-type:
  - type: illustration
- image: assets/images/portfolio/item-6.png
  url: '/portfolio_detail'
  portfolio-type:
  - type: design
  - type: branding
- image: assets/images/portfolio/item-8.png
  url: '/portfolio_detail'
  portfolio-type:
  - type: illustration
  
testimonial-items:
- image: assets/images/portfolio/challengers/관리자메인.png
  content: 제가 맡은 기능은 관리자 페이지입니다. <br> 관리자 메인페이지에는 총 6개의 카테고리로 나뉘어져 있습니다. 상단에는 include를 통해 관리자 모든 페이지에 위와 같이 로고 , 관리자 홈 , 회원 신고 관리 , 카테고리 관리 , 자주하는 질문 관리 , 1:1문의 관리로 이동이 가능하고 메인에는 총 6개로 상단의 페이지를 포함하여 챌린지 관리 , 관리잔 권한 챌린지 만들기 페이지로 나뉩니다.
  
- image: assets/images/portfolio/challengers/회원신고관리.png
  content: 회원 신고 관리 페이지 입니다. <br> 메인에는 테이블 형식으로 회원 신고 목록을 볼 수 있으며 상단에는 검색 하단에는 페이징 처리가 되어있습니다. ajax를 활용하여 피신고자 , 신고자 , 제목을 통해 검색 할 수 있으며 페이징 처리 또한 ajax를 활용하였습니다. 목록을 클릭하여 회원을 회원삭제 또는 회원 정지 기능이 있습니다.  

- image: assets/images/portfolio/challengers/카테고리관리.png
  content: 카테고리 관리 페이지 입니다. <br> 메인 카테고리 총 9개로 이루어져 있고, 클릭하여 상세 페이지로 들어가면 카테고리 수정 , 삭제 기능이 있고 서브 카테고리 추가 , 수정 , 삭제 기능이 있습니다.

- image: assets/images/portfolio/challengers/자주하는질문관리.png
  content: 해당 페이지는 자주하는 질문 관리 페이지입니다. <br> 회원 신고 관리 페이지와 마찬가지로 상단에는 검색과 네 개의 카테고리가 있고 하단에는 페이징 처리가 되어있으며 중단에는 자주하는 질문 목록들이 나열되어있습니다. 검색과 페이징은 ajax를 통해 기능하며 목록을 클릭하여 상세보기 페이지로 이동하게 되면 추가 , 수정 , 삭제 기능이 있습니다.

- image: assets/images/portfolio/challengers/일대일문의관리.png
  content: 1:1문의 관리 페이지입니다. <br> 프로젝트 당시 관리자 페이지는 디자인 보다는 일관성이 있고 UI/UX의 편리성과 친절성이 중요하다고 생각하여 전체적으로 일관성이 있게 디자인 하였습니다. 질문 목록을 클릭하여 상세보기 페이지로 이동하게 되면 회원에게 답변을 하고 회원은 메인 include에 메일 이모티콘과 답변의 갯수가 생섭됩니다.   

- image: assets/images/portfolio/challengers/챌린지관리.png
  content: 챌린지관리 페이지입니다. <br> 회원 페이지에서 챌린지를 생성하거나 관리자권한으로 챌린지를 생성한 모든 챌린지를 9개의 카테고리로 나타냅니다. 다른 기능들과 마찬가지로 상단에는 검색과 카테고리목록 하단에는 페이징 처리가 되어있으며 한 페이지에 12개의 챌린지로 나뉘어 있습니다. 해당 챌린지를 클릭하여 상세보기 페이지로 이동하게 되면, 챌린지의 모든 설정들을 변경할 수 있습니다.
  
- image: assets/images/portfolio/challengers/챌린지개설.png
  content: 관리자 챌린지개설 페이지입니다. <br> 챌린지 개설은 총 5단계로 이루어져 있습니다. <br> 1.세 개의 채크박스를 클릭하여 다음 단계로 넘어 갑니다. <br> 2.다른 회원들에게 챌린지의 공개 유무를 결정합니다. <br> 3.챌린지의 제목 , 인증 방법 , 인증 빈도 , 기간을 정하고 예시 사진을 확인 후 다음 페이지로 넘어 갈 수 있습니다. <br> 4.인증가능 시간과 챌린지 소개 , 소개 사진을 작성 후 마지막 단계로 이동합니다. <br>5.예치금과 비공개 참여 코드 , 최대인원 설정후 챌린지를 개설할 수 있습니다.  
 
challnegers-process:
- icon: assets/images/skills/java.png
- icon: assets/images/skills/html5.png
- icon: assets/images/skills/css.png
- icon: assets/images/skills/js.png
- icon: assets/images/skills/bootstrap.png
- icon: assets/images/skills/jsp.png
- icon: assets/images/skills/oracle.png
- icon: assets/images/skills/eclipse.png
- icon: assets/images/skills/github.png 

contact-title: Contact Info
contact-email: steve.fruits@email.com
